# EXAMPLE USAGE:
#   https://lefthook.dev/configuration/
pre-commit:
  parallel: true
  jobs:
    - name: fmt
      run: rustfmt {staged_files}
      glob: "*.rs"
    - name: clippy
      run: cargo clippy --all-features --workspace -- -D warnings
      glob: "*.rs"
